# @package _global_
type: test_deepac
task: tracking

save_dir: /home/jyj/Projects/DeepAC/workspace/test_rbot_deepac
load_cfg: /home/jyj/Projects/DeepAC/workspace/train_bop_deepac/logs-2024-01-08-15-52-47/train_cfg_gray.yml
load_model: /home/jyj/Projects/DeepAC/workspace/train_bop_deepac/logs-2024-01-08-15-52-47/model_last.ckpt


# 输出设置
output_video: true   # 开启视频输出
output_size: [320, 320]
output_pose: true

# 学习率和超参
fore_learn_rate: 0.2
back_learn_rate: 0.2
gpu_id: '0'
distribution_length: 12

# 数据集设置
data:
  name: RBOT
  dataset_dir: /media/jyj/JYJ/RBOT-gray
  change_background: false
  batch_size_per_gpu: 1
  test_obj_names: ['cat']
  test_slices: ['a_regular']
  skip_frame: 1
  num_correspondence_lines: 200

ray:
  use_ray: true
  n_obj_workers: 1
  n_slice_workers: 1
  n_cpus_per_worker: 1
  n_gpus_per_worker: 0.1
